"""complete schema with subtopic scores and full skill vector

Revision ID: 38ad9e5545af
Revises: e34f4f296f37
Create Date: 2026-04-20 01:51:26.927888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ad9e5545af'
down_revision: Union[str, None] = 'e34f4f296f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subtopic_id', sa.String(length=100), nullable=False),
    sa.Column('subtopic_name', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('avg_time_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('skill_vectors', sa.Column('dsa', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('os', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('dbms', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('cn', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('oops', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('se', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('aptitude', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('guesstimation', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('case_study', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('python', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('java', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('web_tech', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('ai', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('ml', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('dl', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('coa', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('microprocessor', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('compiler', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('toc', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('discrete_math', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('linear_algebra', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('engineering_math', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('statistics', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('crypto', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('graphics', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('mobile', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('skill_vectors', sa.Column('competitive', sa.Numeric(precision=4, scale=2), nullable=True))
    op.drop_column('skill_vectors', 'dynamic_programming')
    op.drop_column('skill_vectors', 'linked_lists')
    op.drop_column('skill_vectors', 'edge_case_thinking')
    op.drop_column('skill_vectors', 'graphs')
    op.drop_column('skill_vectors', 'coding_speed')
    op.drop_column('skill_vectors', 'arrays')
    op.drop_column('skill_vectors', 'trees')
    op.drop_column('skill_vectors', 'communication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_vectors', sa.Column('communication', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('trees', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('arrays', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('coding_speed', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('graphs', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('edge_case_thinking', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('linked_lists', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.add_column('skill_vectors', sa.Column('dynamic_programming', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True))
    op.drop_column('skill_vectors', 'competitive')
    op.drop_column('skill_vectors', 'mobile')
    op.drop_column('skill_vectors', 'graphics')
    op.drop_column('skill_vectors', 'crypto')
    op.drop_column('skill_vectors', 'statistics')
    op.drop_column('skill_vectors', 'engineering_math')
    op.drop_column('skill_vectors', 'linear_algebra')
    op.drop_column('skill_vectors', 'discrete_math')
    op.drop_column('skill_vectors', 'toc')
    op.drop_column('skill_vectors', 'compiler')
    op.drop_column('skill_vectors', 'microprocessor')
    op.drop_column('skill_vectors', 'coa')
    op.drop_column('skill_vectors', 'dl')
    op.drop_column('skill_vectors', 'ml')
    op.drop_column('skill_vectors', 'ai')
    op.drop_column('skill_vectors', 'web_tech')
    op.drop_column('skill_vectors', 'java')
    op.drop_column('skill_vectors', 'python')
    op.drop_column('skill_vectors', 'case_study')
    op.drop_column('skill_vectors', 'guesstimation')
    op.drop_column('skill_vectors', 'aptitude')
    op.drop_column('skill_vectors', 'se')
    op.drop_column('skill_vectors', 'oops')
    op.drop_column('skill_vectors', 'cn')
    op.drop_column('skill_vectors', 'dbms')
    op.drop_column('skill_vectors', 'os')
    op.drop_column('skill_vectors', 'dsa')
    op.drop_table('subtopic_scores')
    # ### end Alembic commands ###
