"""update session and question models

Revision ID: ecc93b800587
Revises: 38ad9e5545af
Create Date: 2026-04-20 12:25:56.455626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecc93b800587'
down_revision: Union[str, None] = '38ad9e5545af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('session_id', sa.UUID(), nullable=False))
    op.add_column('questions', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('subject_id', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('subject_name', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('subtopic_id', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('subtopic_name', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'sessions', ['session_id'], ['id'])
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'expected_answer')
    op.drop_column('questions', 'test_cases')
    op.drop_column('questions', 'company_tag')
    op.add_column('sessions', sa.Column('domain_id', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('subject_id', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('subject_name', sa.String(length=200), nullable=True))
    op.add_column('sessions', sa.Column('skill_field', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('subtopics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('question_type', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('question_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('total_score', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('sessions', sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('sessions', sa.Column('total_time_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('weak_subtopics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('strong_subtopics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('session_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('sessions', 'recording_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('recording_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'session_summary')
    op.drop_column('sessions', 'strong_subtopics')
    op.drop_column('sessions', 'weak_subtopics')
    op.drop_column('sessions', 'total_time_seconds')
    op.drop_column('sessions', 'accuracy')
    op.drop_column('sessions', 'total_score')
    op.drop_column('sessions', 'question_count')
    op.drop_column('sessions', 'question_type')
    op.drop_column('sessions', 'difficulty')
    op.drop_column('sessions', 'subtopics')
    op.drop_column('sessions', 'skill_field')
    op.drop_column('sessions', 'subject_name')
    op.drop_column('sessions', 'subject_id')
    op.drop_column('sessions', 'domain_id')
    op.add_column('questions', sa.Column('company_tag', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('expected_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_number')
    op.drop_column('questions', 'subtopic_name')
    op.drop_column('questions', 'subtopic_id')
    op.drop_column('questions', 'subject_name')
    op.drop_column('questions', 'subject_id')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'session_id')
    # ### end Alembic commands ###
