/**
 * Complete Curriculum Map
 * ========================
 * Defines all domains, subjects, and subtopics for the platform.
 * Phase A → Active now (questions generated by AI)
 * Phase B → Coming Soon (unlocked next semester)
 * Phase C → Coming Soon (unlocked later)
 *
 * TO UNLOCK A SUBJECT: change comingSoon: false
 * No other code changes needed anywhere.
 */

export interface Subtopic {
  id: string;
  name: string;
}

export interface Subject {
  id: string;
  name: string;
  skillField: string; // maps to skill_vector column
  subtopics: Subtopic[];
  comingSoon: boolean;
}

export interface Domain {
  id: string;
  name: string;
  phase: "A" | "B" | "C";
  comingSoon: boolean;
  subjects: Subject[];
}

export const curriculum: Domain[] = [

  // ════════════════════════════════════════════════════
  // DOMAIN 1 — Core Computer Science (Phase A)
  // ════════════════════════════════════════════════════
  {
    id: "core_cs",
    name: "Core Computer Science",
    phase: "A",
    comingSoon: false,
    subjects: [
      {
        id: "dsa",
        name: "Data Structures & Algorithms",
        skillField: "dsa",
        comingSoon: false,
        subtopics: [
          { id: "dsa_complexity", name: "Complexity Analysis (Big O, Time & Space)" },
          { id: "dsa_arrays", name: "Arrays & Strings" },
          { id: "dsa_linked_lists", name: "Linked Lists (Singly, Doubly, Circular)" },
          { id: "dsa_stacks_queues", name: "Stacks & Queues" },
          { id: "dsa_trees", name: "Trees & Binary Trees" },
          { id: "dsa_bst", name: "BST, AVL Trees & B-Trees" },
          { id: "dsa_heaps", name: "Heaps & Priority Queues" },
          { id: "dsa_hashing", name: "Hashing & Hash Tables" },
          { id: "dsa_graphs", name: "Graphs (BFS, DFS, Representation)" },
          { id: "dsa_shortest_path", name: "Shortest Path Algorithms" },
          { id: "dsa_mst", name: "Minimum Spanning Trees" },
          { id: "dsa_sorting", name: "Sorting Algorithms" },
          { id: "dsa_searching", name: "Searching Algorithms" },
          { id: "dsa_dp", name: "Dynamic Programming" },
          { id: "dsa_greedy", name: "Greedy Algorithms" },
          { id: "dsa_backtracking", name: "Backtracking & Recursion" },
          { id: "dsa_divide_conquer", name: "Divide & Conquer" },
          { id: "dsa_segment_trees", name: "Segment Trees & Fenwick Trees" },
          { id: "dsa_np", name: "NP-Completeness & Complexity Classes" },
        ],
      },
      {
        id: "os",
        name: "Operating Systems",
        skillField: "os",
        comingSoon: false,
        subtopics: [
          { id: "os_intro", name: "Introduction & OS Types" },
          { id: "os_process", name: "Process Management & PCB" },
          { id: "os_scheduling", name: "CPU Scheduling Algorithms" },
          { id: "os_threads", name: "Threads & Concurrency" },
          { id: "os_deadlock", name: "Deadlocks (Detection, Prevention, Avoidance)" },
          { id: "os_semaphore", name: "Semaphores & Mutex" },
          { id: "os_memory", name: "Memory Management & Paging" },
          { id: "os_virtual", name: "Virtual Memory & Page Replacement" },
          { id: "os_filesystem", name: "File Systems" },
          { id: "os_disk", name: "Disk Scheduling" },
          { id: "os_ipc", name: "Inter-Process Communication" },
          { id: "os_distributed", name: "Distributed OS Concepts" },
        ],
      },
      {
        id: "dbms",
        name: "Database Management Systems",
        skillField: "dbms",
        comingSoon: false,
        subtopics: [
          { id: "dbms_intro", name: "Introduction & DBMS Architecture" },
          { id: "dbms_er", name: "ER Model & Database Design" },
          { id: "dbms_relational", name: "Relational Model & Relational Algebra" },
          { id: "dbms_sql", name: "SQL (DDL, DML, DCL, TCL)" },
          { id: "dbms_joins", name: "Joins, Subqueries & Views" },
          { id: "dbms_normalization", name: "Normalization (1NF to BCNF)" },
          { id: "dbms_acid", name: "ACID Properties & Transactions" },
          { id: "dbms_concurrency", name: "Concurrency Control & Locking" },
          { id: "dbms_indexing", name: "Indexing & Query Optimization" },
          { id: "dbms_recovery", name: "Backup, Recovery & Database Security" },
          { id: "dbms_nosql", name: "NoSQL Databases & CAP Theorem" },
        ],
      },
      {
        id: "cn",
        name: "Computer Networks",
        skillField: "cn",
        comingSoon: false,
        subtopics: [
          { id: "cn_intro", name: "Introduction & Network Types (LAN, MAN, WAN)" },
          { id: "cn_osi", name: "OSI Model & TCP/IP Stack" },
          { id: "cn_physical", name: "Physical Layer & Transmission Media" },
          { id: "cn_datalink", name: "Data Link Layer & MAC Protocols" },
          { id: "cn_network", name: "Network Layer & IP Addressing" },
          { id: "cn_subnetting", name: "Subnetting & Routing Protocols" },
          { id: "cn_transport", name: "Transport Layer (TCP vs UDP)" },
          { id: "cn_application", name: "Application Layer (HTTP, DNS, SMTP)" },
          { id: "cn_security", name: "Network Security" },
          { id: "cn_socket", name: "Socket Programming" },
          { id: "cn_congestion", name: "Congestion Control & Flow Control" },
        ],
      },
      {
        id: "oops",
        name: "Object Oriented Programming",
        skillField: "oops",
        comingSoon: false,
        subtopics: [
          { id: "oops_classes", name: "Classes, Objects & Constructors" },
          { id: "oops_inheritance", name: "Inheritance & Types of Inheritance" },
          { id: "oops_polymorphism", name: "Polymorphism & Virtual Functions" },
          { id: "oops_encapsulation", name: "Encapsulation & Abstraction" },
          { id: "oops_operator", name: "Operator Overloading & Type Conversion" },
          { id: "oops_templates", name: "Templates & Generic Programming" },
          { id: "oops_exception", name: "Exception Handling" },
          { id: "oops_file_io", name: "File I/O Operations" },
          { id: "oops_stl", name: "STL & Collections" },
          { id: "oops_solid", name: "SOLID Principles & Design Patterns" },
        ],
      },
      {
        id: "se",
        name: "Software Engineering",
        skillField: "se",
        comingSoon: false,
        subtopics: [
          { id: "se_sdlc", name: "SDLC Models (Waterfall, Agile, Spiral)" },
          { id: "se_requirements", name: "Requirements Engineering & SRS" },
          { id: "se_design", name: "Software Design Principles" },
          { id: "se_coupling", name: "Coupling, Cohesion & Modularity" },
          { id: "se_testing", name: "Software Testing Strategies" },
          { id: "se_project", name: "Project Management & COCOMO" },
          { id: "se_uml", name: "UML Diagrams" },
          { id: "se_metrics", name: "Software Metrics & Quality" },
        ],
      },
      {
        id: "system_design",
        name: "System Design",
        skillField: "system_design",
        comingSoon: false,
        subtopics: [
          { id: "sd_scalability", name: "Scalability & Load Balancing" },
          { id: "sd_caching", name: "Caching Strategies (Redis, CDN)" },
          { id: "sd_database", name: "Database Design at Scale" },
          { id: "sd_microservices", name: "Microservices Architecture" },
          { id: "sd_queues", name: "Message Queues (Kafka, RabbitMQ)" },
          { id: "sd_api", name: "API Design (REST vs GraphQL)" },
          { id: "sd_rate_limiting", name: "Rate Limiting & Throttling" },
          { id: "sd_distributed", name: "Distributed Systems & CAP Theorem" },
          { id: "sd_availability", name: "High Availability & Fault Tolerance" },
          { id: "sd_realworld", name: "Real-world Design (Twitter, YouTube, Uber)" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 2 — Programming Languages (Phase B)
  // ════════════════════════════════════════════════════
  {
    id: "programming",
    name: "Programming Languages",
    phase: "B",
    comingSoon: true,
    subjects: [
      {
        id: "python",
        name: "Python Programming",
        skillField: "python",
        comingSoon: true,
        subtopics: [
          { id: "py_basics", name: "Python Basics & Data Types" },
          { id: "py_functions", name: "Functions, Modules & Packages" },
          { id: "py_file", name: "File Handling" },
          { id: "py_oop", name: "OOP in Python" },
          { id: "py_regex", name: "Regular Expressions & Exception Handling" },
          { id: "py_db", name: "Database Connectivity" },
          { id: "py_libraries", name: "NumPy & Pandas Basics" },
          { id: "py_fastapi", name: "FastAPI & REST APIs" },
          { id: "py_frameworks", name: "Django/Flask Basics" },
        ],
      },
      {
        id: "java",
        name: "Java Programming",
        skillField: "java",
        comingSoon: true,
        subtopics: [
          { id: "java_basics", name: "Java Basics & OOP Concepts" },
          { id: "java_classes", name: "Classes, Methods & Inheritance" },
          { id: "java_exception", name: "Exception Handling & Multithreading" },
          { id: "java_io", name: "I/O Streams & File Handling" },
          { id: "java_jdbc", name: "JDBC & Database Connectivity" },
          { id: "java_servlets", name: "Servlets & JSP" },
          { id: "java_collections", name: "Collections Framework" },
        ],
      },
      {
        id: "web_tech",
        name: "Web Technologies & Node.js",
        skillField: "web_tech",
        comingSoon: true,
        subtopics: [
          { id: "web_html_css", name: "HTML, CSS & JavaScript Core" },
          { id: "web_dom", name: "DOM Manipulation & Events" },
          { id: "web_nodejs", name: "Node.js Architecture & Event Loop" },
          { id: "web_express", name: "Express.js & REST APIs" },
          { id: "web_php", name: "PHP & Server-side Scripting" },
          { id: "web_auth", name: "Authentication (JWT, OAuth2, Sessions)" },
          { id: "web_websocket", name: "WebSockets & Real-time Communication" },
          { id: "web_security", name: "Web Security (XSS, CSRF, CORS)" },
          { id: "web_performance", name: "Web Performance Optimization" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 3 — AI & Machine Learning (Phase B)
  // ════════════════════════════════════════════════════
  {
    id: "ai_ml",
    name: "AI & Machine Learning",
    phase: "B",
    comingSoon: true,
    subjects: [
      {
        id: "ai",
        name: "Artificial Intelligence",
        skillField: "ai",
        comingSoon: true,
        subtopics: [
          { id: "ai_search", name: "Problem Solving & Search (BFS, DFS, A*)" },
          { id: "ai_heuristic", name: "Heuristic Search Strategies" },
          { id: "ai_knowledge", name: "Knowledge Representation & Logic" },
          { id: "ai_probabilistic", name: "Probabilistic Reasoning & Bayesian Networks" },
          { id: "ai_planning", name: "Planning & Learning Agents" },
          { id: "ai_expert", name: "Expert Systems" },
          { id: "ai_game", name: "Game Playing (Minimax, Alpha-Beta Pruning)" },
        ],
      },
      {
        id: "ml",
        name: "Machine Learning",
        skillField: "ml",
        comingSoon: true,
        subtopics: [
          { id: "ml_intro", name: "Introduction & Types of ML" },
          { id: "ml_regression", name: "Linear & Polynomial Regression" },
          { id: "ml_classification", name: "Classification (Logistic Regression, SVM)" },
          { id: "ml_trees", name: "Decision Trees & Ensemble Methods" },
          { id: "ml_nn", name: "Neural Networks & Backpropagation" },
          { id: "ml_unsupervised", name: "Unsupervised Learning & Clustering" },
          { id: "ml_dimensionality", name: "Dimensionality Reduction (PCA, LDA)" },
          { id: "ml_evaluation", name: "Model Evaluation & Metrics" },
        ],
      },
      {
        id: "dl",
        name: "Deep Learning",
        skillField: "dl",
        comingSoon: true,
        subtopics: [
          { id: "dl_fundamentals", name: "Neural Network Fundamentals & Perceptrons" },
          { id: "dl_feedforward", name: "Feedforward Networks & Backpropagation" },
          { id: "dl_gradient", name: "Gradient Descent Variants (SGD, Adam, RMSProp)" },
          { id: "dl_regularization", name: "Regularization (Dropout, Batch Norm, L2)" },
          { id: "dl_cnn", name: "Convolutional Neural Networks" },
          { id: "dl_rnn", name: "Recurrent Neural Networks & LSTM" },
          { id: "dl_transformers", name: "Transformers & Attention Mechanism" },
          { id: "dl_autoencoders", name: "Autoencoders & Representation Learning" },
          { id: "dl_transfer", name: "Transfer Learning & MLOps" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 4 — Systems & Architecture (Phase B)
  // ════════════════════════════════════════════════════
  {
    id: "systems",
    name: "Systems & Architecture",
    phase: "B",
    comingSoon: true,
    subjects: [
      {
        id: "coa",
        name: "Computer Organization & Architecture",
        skillField: "coa",
        comingSoon: true,
        subtopics: [
          { id: "coa_org", name: "Basic Computer Organization & ALU" },
          { id: "coa_isa", name: "Instruction Set Architecture (RISC vs CISC)" },
          { id: "coa_assembly", name: "Assembly Language Programming" },
          { id: "coa_memory", name: "Memory Hierarchy & Cache" },
          { id: "coa_io", name: "I/O Systems & Interfacing" },
          { id: "coa_pipeline", name: "Pipeline Processing" },
          { id: "coa_float", name: "Floating Point Representation (IEEE 754)" },
        ],
      },
      {
        id: "microprocessor",
        name: "Microprocessor & Assembly (8085)",
        skillField: "microprocessor",
        comingSoon: true,
        subtopics: [
          { id: "mp_arch", name: "8085 Architecture & MPU" },
          { id: "mp_assembly", name: "Assembly Language Programming" },
          { id: "mp_io", name: "I/O Interfacing & Memory Mapping" },
          { id: "mp_interrupts", name: "Interrupts & Subroutines" },
          { id: "mp_counters", name: "Counters & Time Delays" },
        ],
      },
      {
        id: "compiler",
        name: "Compiler Design",
        skillField: "compiler",
        comingSoon: true,
        subtopics: [
          { id: "cd_phases", name: "Phases of a Compiler" },
          { id: "cd_lexical", name: "Lexical Analysis & Tokens" },
          { id: "cd_syntax", name: "Syntax Analysis & Parsing (SLR, LALR, CLR)" },
          { id: "cd_semantic", name: "Semantic Analysis & SDT" },
          { id: "cd_intermediate", name: "Intermediate Code Generation" },
          { id: "cd_optimization", name: "Code Optimization" },
          { id: "cd_generation", name: "Code Generation & Register Allocation" },
        ],
      },
      {
        id: "toc",
        name: "Theory of Computation",
        skillField: "toc",
        comingSoon: true,
        subtopics: [
          { id: "toc_fa", name: "Finite Automata (DFA, NFA)" },
          { id: "toc_regex", name: "Regular Expressions & Languages" },
          { id: "toc_cfg", name: "Context-Free Grammars & Languages" },
          { id: "toc_pda", name: "Pushdown Automata" },
          { id: "toc_tm", name: "Turing Machines" },
          { id: "toc_decidability", name: "Decidability & Undecidability" },
          { id: "toc_np", name: "P, NP & NP-Completeness" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 5 — Mathematics (Phase C)
  // ════════════════════════════════════════════════════
  {
    id: "mathematics",
    name: "Mathematics",
    phase: "C",
    comingSoon: true,
    subjects: [
      {
        id: "discrete_math",
        name: "Discrete Mathematics",
        skillField: "discrete_math",
        comingSoon: true,
        subtopics: [
          { id: "dm_sets", name: "Set Theory & Relations" },
          { id: "dm_logic", name: "Mathematical Logic & Proof Techniques" },
          { id: "dm_combinatorics", name: "Combinatorics & Counting" },
          { id: "dm_graph", name: "Graph Theory" },
          { id: "dm_algebra", name: "Algebraic Structures (Groups, Rings)" },
        ],
      },
      {
        id: "linear_algebra",
        name: "Linear Algebra",
        skillField: "linear_algebra",
        comingSoon: true,
        subtopics: [
          { id: "la_systems", name: "Systems of Linear Equations" },
          { id: "la_vector", name: "Vector Spaces & Subspaces" },
          { id: "la_eigen", name: "Eigenvalues & Eigenvectors" },
          { id: "la_transform", name: "Linear Transformations" },
          { id: "la_matrix", name: "Matrix Operations & Decomposition" },
        ],
      },
      {
        id: "engineering_math",
        name: "Engineering Mathematics",
        skillField: "engineering_math",
        comingSoon: true,
        subtopics: [
          { id: "em_ode", name: "Ordinary Differential Equations" },
          { id: "em_laplace", name: "Laplace Transforms" },
          { id: "em_fourier", name: "Fourier Series & Transforms" },
          { id: "em_vector", name: "Vector Calculus" },
        ],
      },
      {
        id: "statistics",
        name: "Statistics & Probability",
        skillField: "statistics",
        comingSoon: true,
        subtopics: [
          { id: "st_probability", name: "Probability Theory & Axioms" },
          { id: "st_distributions", name: "Probability Distributions" },
          { id: "st_bayesian", name: "Bayesian Statistics" },
          { id: "st_hypothesis", name: "Hypothesis Testing" },
          { id: "st_regression", name: "Regression Analysis" },
          { id: "st_2d", name: "Two-Dimensional Random Variables" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 6 — Specialized Topics (Phase C)
  // ════════════════════════════════════════════════════
  {
    id: "specialized",
    name: "Specialized Topics",
    phase: "C",
    comingSoon: true,
    subjects: [
      {
        id: "crypto",
        name: "Cryptography & Network Security",
        skillField: "crypto",
        comingSoon: true,
        subtopics: [
          { id: "cr_classical", name: "Classical Cryptography & Ciphers" },
          { id: "cr_symmetric", name: "Symmetric Encryption (DES, AES)" },
          { id: "cr_asymmetric", name: "Asymmetric Encryption (RSA, PKI)" },
          { id: "cr_hashing", name: "Hashing Algorithms (MD5, SHA)" },
          { id: "cr_key", name: "Key Management & Diffie-Hellman" },
          { id: "cr_ssl", name: "SSL/TLS & Web Security" },
          { id: "cr_attacks", name: "Firewalls, VPN & Common Attacks" },
        ],
      },
      {
        id: "graphics",
        name: "Computer Graphics",
        skillField: "graphics",
        comingSoon: true,
        subtopics: [
          { id: "cg_primitives", name: "Output Primitives & Drawing Algorithms" },
          { id: "cg_2d", name: "2D Transformations & Viewing Pipeline" },
          { id: "cg_3d", name: "3D Concepts & Transformations" },
          { id: "cg_clipping", name: "Clipping Algorithms" },
          { id: "cg_shading", name: "Visible Surface Detection & Shading" },
        ],
      },
      {
        id: "mobile",
        name: "Mobile App Development",
        skillField: "mobile",
        comingSoon: true,
        subtopics: [
          { id: "mob_android", name: "Android Fundamentals & Java/Kotlin" },
          { id: "mob_ui", name: "UI Design & Activity Lifecycle" },
          { id: "mob_threads", name: "Threads, Services & Notifications" },
          { id: "mob_data", name: "Native Data Handling & SQLite" },
          { id: "mob_testing", name: "Testing & Deployment" },
        ],
      },
      {
        id: "competitive",
        name: "Competitive Programming",
        skillField: "competitive",
        comingSoon: true,
        subtopics: [
          { id: "cp_complexity", name: "Time Complexity & Optimization" },
          { id: "cp_advanced_ds", name: "Advanced Data Structures" },
          { id: "cp_graphs", name: "Advanced Graph Algorithms" },
          { id: "cp_number", name: "Number Theory & Combinatorics" },
          { id: "cp_strings", name: "String Algorithms (KMP, Z, Trie)" },
          { id: "cp_game", name: "Game Theory & Probability" },
          { id: "cp_dp", name: "Advanced Dynamic Programming" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════
  // DOMAIN 7 — Placement Preparation (Phase A — Active Now)
  // ════════════════════════════════════════════════════
  {
    id: "placement_prep",
    name: "Placement Preparation",
    phase: "A",
    comingSoon: false,
    subjects: [
      {
        id: "aptitude",
        name: "Aptitude & Reasoning",
        skillField: "aptitude",
        comingSoon: false,
        subtopics: [
          { id: "apt_number_systems", name: "Number Systems & Divisibility" },
          { id: "apt_percentages", name: "Percentages & Profit-Loss" },
          { id: "apt_time_speed", name: "Time, Speed & Distance" },
          { id: "apt_time_work", name: "Time & Work" },
          { id: "apt_ratio", name: "Ratio, Proportion & Mixtures" },
          { id: "apt_permutation", name: "Permutations & Combinations" },
          { id: "apt_probability", name: "Probability" },
          { id: "apt_series", name: "Series & Patterns" },
          { id: "apt_blood_relations", name: "Blood Relations" },
          { id: "apt_directions", name: "Directions & Distances" },
          { id: "apt_coding_decoding", name: "Coding-Decoding" },
          { id: "apt_syllogisms", name: "Syllogisms & Logical Deduction" },
          { id: "apt_puzzles", name: "Puzzles & Seating Arrangements" },
          { id: "apt_reading", name: "Reading Comprehension" },
          { id: "apt_grammar", name: "Grammar & Sentence Correction" },
          { id: "apt_vocabulary", name: "Vocabulary & Synonyms/Antonyms" },
          { id: "apt_para_jumbles", name: "Para Jumbles" },
        ],
      },
      {
        id: "guesstimation",
        name: "Guesstimation",
        skillField: "guesstimation",
        comingSoon: false,
        subtopics: [
          { id: "guess_fermi", name: "Fermi Problems & Estimation Frameworks" },
          { id: "guess_market", name: "Market Sizing Problems" },
          { id: "guess_back_envelope", name: "Back-of-Envelope Calculations" },
          { id: "guess_assumption", name: "Assumption-based Reasoning" },
          { id: "guess_sanity_check", name: "Sanity Checking Estimates" },
        ],
      },
      {
        id: "case_study",
        name: "Case Studies",
        skillField: "case_study",
        comingSoon: false,
        subtopics: [
          { id: "cs_product", name: "Product Case Studies" },
          { id: "cs_business", name: "Business Problem Solving" },
          { id: "cs_tech", name: "Tech Company Case Analysis" },
          { id: "cs_data_driven", name: "Data-driven Decision Making" },
          { id: "cs_root_cause", name: "Root Cause Analysis" },
        ],
      },
    ],
  },
];

// ─── Helper exports ───────────────────────────────────────────────────────────

export const allDomains = curriculum.map(d => d.name);

export const activeDomains = curriculum.filter(d => !d.comingSoon);

export const allSubjects = curriculum.flatMap(d => d.subjects);

export const activeSubjects = allSubjects.filter(s => !s.comingSoon);

export const getSubjectById = (id: string) =>
  allSubjects.find(s => s.id === id);

export const getSubtopicsBySubject = (subjectId: string) =>
  getSubjectById(subjectId)?.subtopics ?? [];